// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfr8A9SdnQWdkDKST-UxDReU1Fmsa_YE',
    appId: '1:513309634754:web:63d503aa8ead4a26a6cb5b',
    messagingSenderId: '513309634754',
    projectId: 'mbti-14d44',
    authDomain: 'mbti-14d44.firebaseapp.com',
    storageBucket: 'mbti-14d44.appspot.com',
    measurementId: 'G-7336VPFKHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXFq0F48x24UqNPpqH9DHzYPNp6CQw5M',
    appId: '1:513309634754:android:d86fb4596870f9eba6cb5b',
    messagingSenderId: '513309634754',
    projectId: 'mbti-14d44',
    storageBucket: 'mbti-14d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZpjVfzsoSSEDZo8-m1rUjVefH1cfq8A',
    appId: '1:513309634754:ios:93f8e222417bd947a6cb5b',
    messagingSenderId: '513309634754',
    projectId: 'mbti-14d44',
    storageBucket: 'mbti-14d44.appspot.com',
    iosBundleId: 'com.example.mbtiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZpjVfzsoSSEDZo8-m1rUjVefH1cfq8A',
    appId: '1:513309634754:ios:93f8e222417bd947a6cb5b',
    messagingSenderId: '513309634754',
    projectId: 'mbti-14d44',
    storageBucket: 'mbti-14d44.appspot.com',
    iosBundleId: 'com.example.mbtiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsfr8A9SdnQWdkDKST-UxDReU1Fmsa_YE',
    appId: '1:513309634754:web:9b428b6ee6200b67a6cb5b',
    messagingSenderId: '513309634754',
    projectId: 'mbti-14d44',
    authDomain: 'mbti-14d44.firebaseapp.com',
    storageBucket: 'mbti-14d44.appspot.com',
    measurementId: 'G-Z12JPXNKWY',
  );
}
